#!/bin/bash

set -o errexit
set -o xtrace

ROOT_DIR=$(cd $(dirname $0)/../sources/pxc; pwd -P)
SCRIPTS_DIR=$(cd $(dirname $0)/../local; pwd -P)
SOURCE_IMAGE=${1:-centos:7}

RESULTS_ROOT_DIR=$(cd $(dirname $0)/../results/bld.pxc; pwd -P)

docker run --rm \
    --cap-add SYS_PTRACE \
    --mount type=bind,source=${ROOT_DIR},destination=/tmp/pxc57 \
    --mount type=bind,source=${SCRIPTS_DIR},destination=/tmp/scripts \
    --mount type=bind,source=${RESULTS_ROOT_DIR},destination=/tmp/results \
    public.ecr.aws/e7j3v3n0/pxc-build:${SOURCE_IMAGE//[:\/]/-} \
    sh -c "
    set -o errexit
    set -o xtrace

    export JOB_CMAKE='${JOB_CMAKE}'
    export COMPILER='${COMPILER}'
    export CMAKE_BUILD_TYPE='${CMAKE_BUILD_TYPE}'
    export CMAKE_OPTS='${CMAKE_OPTS}'
    export MAKE_OPTS='${MAKE_OPTS}'
    export BUILD_COMMENT='${BUILD_COMMENT}'
    export TAG='${TAG}'
    export DIST_NAME='${DIST_NAME}'
    export SSL_VER='${SSL_VER}'
    export ANALYZER_OPTS='${ANALYZER_OPTS}'

    mkdir -p /tmp/results

    # 5.7 legacy build script needs 'target' directory inside src directory
    # sudo rm -rf /tmp/pxc57/target
    sudo mkdir -p /tmp/pxc57/target

    cp -r /tmp/source_downloads /tmp/results/source_downloads
    sudo chown -R mysql:mysql /tmp/pxc57/wsrep /tmp/pxc57/mysql-test /tmp/pxc57/target || :
    bash -x /tmp/scripts/build-binary-pxc-parallel-mtr /tmp/results /tmp/pxc57

    sudo mkdir -p /tmp/pxc57/results
    sudo mv /tmp/results/*.tar.gz /tmp/pxc57/results/
    sudo chown -R $(id -u):$(id -g) /tmp/pxc57/results /tmp/pxc57/wsrep /tmp/pxc57/mysql-test /tmp/pxc57/target
"