#!/bin/bash

#  possible vars:
#      GIT_REPO
#      BRANCH
#      PXB24_REPO
#      PXB24_BRANCH

set -o errexit
set -o xtrace

SOURCE_NAME=${1:-'ALL'}

ROOT_DIR=$(cd $(dirname $0)/..; pwd -P)/sources

if [ ! -d "${ROOT_DIR}" ]; then
    mkdir -p ${ROOT_DIR}
fi

# ==================== PXC ====================
# It should be PXC, not PXC80, but for integration with Jenkins groovy...
if [ "$SOURCE_NAME" == 'PXC80' -o "$SOURCE_NAME" == 'ALL' ]; then
    PXC_ROOT_DIR="${ROOT_DIR}/pxc"

    sudo rm -rf ${PXC_ROOT_DIR}
    if [[ "${GIT_REPO}" =~ "private" ]]; then
        GIT_REPO=$(echo ${GIT_REPO} | sed -e "s|github|${PXC_SECRET_TOKEN}@github|")
    fi
    echo cloning pxc repo...
    git clone --depth 1 "${GIT_REPO:-https://github.com/percona/percona-xtradb-cluster}" "${PXC_ROOT_DIR}"  -b "${BRANCH}"
    echo cloning pxc repo...DONE

    pushd $PXC_ROOT_DIR
        git reset --hard
        git clean -xdf

        mkdir ./target

		rm -rf percona-xtradb-cluster-galera || true
        echo cloning galera repo...
		git submodule deinit -f . || true
		git submodule init
		git submodule update
        echo cloning galera repo...DONE

	    pushd percona-xtradb-cluster-galera
            echo cloning wsrep-API repo...
		    git submodule deinit -f . || true
		    git submodule init
		    git submodule update
            echo cloning wsrep-API repo...DONE
        popd
    popd
fi


# ==================== PXB24 ====================

if [ "$SOURCE_NAME" == 'PXB24' -o "$SOURCE_NAME" == 'ALL' ]; then
    PXB24_ROOT_DIR="${ROOT_DIR}/pxb24"
 
    sudo rm -rf ${PXB24_ROOT_DIR}

    git clone "${PXB24_REPO:-https://github.com/percona/percona-xtrabackup}" "${PXB24_ROOT_DIR}"

    pushd $PXB24_ROOT_DIR
        if [ -n "${PXB24_REPO}" ]; then
            git remote set-url origin "${PXB24_REPO}"
            git fetch --all
        fi

        git reset --hard
        git clean -xdf

        if [ -n "${PXB24_BRANCH}" ]; then
            git checkout "${PXB24_BRANCH}"
            git checkout -b "tag-${PXB24_BRANCH}"
        fi
        if [ -n "${PXB24_REPO}" -a -n "${PXB24_BRANCH}" ]; then
            git pull origin ${PXB24_BRANCH}
        fi
    popd
fi
