#!/bin/bash
#
# Execute this tool to test binary releases
#
#  possible jenkins vars:
#      CMAKE_BUILD_TYPE = (RelWithDebInfo Debug)
#      DEFAULT_TESTING = (yes no)
#      MTR_ARGS
#      MTR_REPEAT
#      FULL_MTR = (yes no)
#      GALERA_PARALLEL_RUN
#      MTR_SUITES
#      PARALLEL_RUN
#      DOCKER_OS

set -o errexit
set -o xtrace

WORKDIR_ABS=$(cd ${1:-./build/pxc}; pwd -P)
rm -fr ${WORKDIR_ABS}/PXC
mkdir -p ${WORKDIR_ABS}/PXC/sql
tar -C ${WORKDIR_ABS}/PXC --strip-components=1 -zxpf $(ls $WORKDIR_ABS/*.tar.gz | head -1)
ls -la ${WORKDIR_ABS}
ls -la ${WORKDIR_ABS}/PXC
ls -la ${WORKDIR_ABS}/PXC/sql

# PXB >>>
PXB24_WORKDIR=$WORKDIR_ABS/pxb24
PXB80_WORKDIR=$WORKDIR_ABS/pxb80
ls -la $PXB24_WORKDIR
ls -la $PXB80_WORKDIR

PXB24_TAR=$(ls $PXB24_WORKDIR/{percona-xtrabackup-2.*.tar.gz,pxb24.tar.gz}  | awk -F'/' '{print $NF}')
PXB80_TAR=$(ls $PXB80_WORKDIR/{percona-xtrabackup-8.*.tar.gz,pxb80.tar.gz}  | awk -F'/' '{print $NF}')

mkdir -p ${PXB24_WORKDIR}/target
mkdir -p ${PXB80_WORKDIR}/target
tar -xzf $PXB24_WORKDIR/$PXB24_TAR --exclude='man' --exclude='*-test' -C ${PXB24_WORKDIR}/target
tar -xzf $PXB80_WORKDIR/$PXB80_TAR --exclude='man' --exclude='*-test' -C ${PXB80_WORKDIR}/target

mv ${PXB24_WORKDIR}/target/$(ls ${PXB24_WORKDIR}/target | grep percona-xtrabackup-2) ${PXB24_WORKDIR}/target/pxb-2.4
mv ${PXB80_WORKDIR}/target/$(ls ${PXB80_WORKDIR}/target | grep percona-xtrabackup-8) ${PXB80_WORKDIR}/target/pxb-8.0
ls -la ${PXB24_WORKDIR}/target
ls -la ${PXB80_WORKDIR}/target

mkdir -p ${WORKDIR_ABS}/PXC/bin/pxc_extra/pxb-2.4
mkdir -p ${WORKDIR_ABS}/PXC/bin/pxc_extra/pxb-8.0
cp -v -r ${PXB24_WORKDIR}/target/pxb-2.4/{bin,lib} ${WORKDIR_ABS}/PXC/bin/pxc_extra/pxb-2.4
cp -v -r ${PXB80_WORKDIR}/target/pxb-8.0/{bin,lib} ${WORKDIR_ABS}/PXC/bin/pxc_extra/pxb-8.0
# PXB <<<

export WSREP_PROVIDER=${WORKDIR_ABS}/PXC/lib/libgalera_smm.so
cd ${WORKDIR_ABS}/PXC/mysql-test
TESTCASE_TIMEOUT=90
# CentOS 7
if [[ -f /opt/rh/devtoolset-8/enable ]]; then
    source /opt/rh/devtoolset-8/enable
fi

JEMALLOC=$(find /lib* /usr/lib* /usr/local/lib* -type f -name 'libjemalloc.so*' | head -n1)
EATMYDATA=$(find /lib* /usr/lib* /usr/local/lib* -type f -name '*eatmyda*.so*' | head -n1)

if [[ -z "${EATMYDATA}" ]]; then
  echo "No libeatmydata.so lib found"
  exit 1
fi

if [[ -z "${JEMALLOC}" ]]; then
  echo "No jemalloc lib found"
  exit 1
fi
#MTR_ARGS+="  --big-test "


if [[ -n "${MTR_REPEAT}" ]]; then
  MTR_ARGS+=" --repeat=${MTR_REPEAT}"
fi

if [[ "${MTR_ARGS}" == *"--suite=max_parts"* ]]; then
    TESTCASE_TIMEOUT=$((TESTCASE_TIMEOUT * 3))
fi

if [[ $MTR_ARGS == *"--big-test"* ]] || [[ $MTR_ARGS == *"--only-big-test"* ]]; then
    TESTCASE_TIMEOUT=$((TESTCASE_TIMEOUT * 2))
fi

status=0
#
# Running MTR test cases
if [[ "${DEFAULT_TESTING}" != "no" ]]; then

    if [[ "${ANALYZER_OPTS}" == *WITH_VALGRIND=ON* ]]; then
        MYSQLD_ENV="${ADD_TO_LD_PRELOAD:-}${EATMYDATA}"
    else
        MYSQLD_ENV="${ADD_TO_LD_PRELOAD:-}${JEMALLOC}:${EATMYDATA}"
    fi
    mkdir mtr_var
    if [ ${FULL_MTR} == "no" ]; then
        ARRAY_MTR_SUITES=($(echo $MTR_SUITES | sed 's/,/ /g'))
        for suite in "${ARRAY_MTR_SUITES[@]}"; do
	        if [[ "$suite" == *"galera"* ]]; then
	            WORKER=$GALERA_PARALLEL_RUN
			else
	            WORKER=$PARALLEL_RUN
			fi
	        echo "Running MTR suite: $suite"
            # -p for suites like engines/funcs
	        # mkdir -p $PWD/var_${suite}
            df -h
            du /dev/shm
            mount
            ls -la /dev/shm
            cat /proc/meminfo

            start=`date +%s`

	        MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
	           --result-file --suite=$suite \
	           --force --mysqld-env="LD_PRELOAD=${MYSQLD_ENV}" \
	           --max-test-fail=0 \
	           --suite-timeout=9999 --parallel $WORKER \
	           --port-group-size=20 \
	           --testcase-timeout=${TESTCASE_TIMEOUT} \
               ${MTR_ARGS} \
               --junit-output=${WORKDIR_ABS}/junit_${suite}.xml \
               --junit-package="${DOCKER_OS}.${CMAKE_BUILD_TYPE}.${suite}" || true

            ln -s $PWD/var $PWD/var_${suite}
            rsync -a --prune-empty-dirs --include '*/' --include '*.err' --exclude '*' $PWD/var_${suite} $PWD/mtr_var

            # mv $PWD/var_${suite} $PWD/mtr_var
	        killall -9 mysqld || true
		    rm -rf $PWD/var_${suite}

	        end=`date +%s`
            runtime=$((end-start))
            echo KH,SUITE,${suite},time,$runtime

		done

    else
        echo "Running full MTR"
		mkdir var

        MTR_BUILD_THREAD=auto ./mysql-test-run.pl \
           --result-file --mysqld-env="LD_PRELOAD=${MYSQLD_ENV}" \
           --force --xml-report=${WORKDIR_ABS}/mtr.xml \
           --max-test-fail=0 \
           --suite-timeout=9999 --parallel $PARALLEL_RUN \
           --port-group-size=20 --vardir=var \
           --testcase-timeout=${TESTCASE_TIMEOUT} \
           ${MTR_ARGS} \
           --junit-output=${WORKDIR_ABS}/junit.full_mtr.xml \
           --junit-package="${DOCKER_OS}.${CMAKE_BUILD_TYPE}.full_mtr" || true

        mv $PWD/var $PWD/mtr_var
        killall -9 mysqld || true
    fi
fi

# Convert Latin1(ISO-8859-1) into browser readable UTF-8
for file in $(find ${WORKDIR_ABS}/ -maxdepth 1 -name "*.xml"); do
    iconv -c -t UTF-8 ${file} | tr -cd '[:print:]\n\r' > ${file}-converted
    mv ${file}-converted ${file}
done

exit $status
